spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cuisine-connect-db
    username: derrickmadumere
    password: madumere
    driver-class-name: org.postgresql.Driver
  jpa:
      open-in-view: true
      properties:
        hibernate:
          format_sql: true
          show_sql: false
          use_sql_comments: true
      hibernate:
        ddl-auto: update
server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: on_param
cloudinary:
  cloud-name: dahpyu601
  api:
    key: 512538252244163
    secret: fZ_cCYr2diy2OMmGKlL1lu_2L7M
