spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cuisine-connect-db
    username: derrickmadumere
    password: madumere
    driver-class-name: org.postgresql.Driver
  jpa:
      open-in-view: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          show_sql: false
          use_sql_comments: true
      hibernate:
        ddl-auto: validate
server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: on_param
